-- ########################################################
-- # MASTER SCHEMA FOR DRESSFLOW - SUPABASE (SECURED + AVATARS)
-- ########################################################

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY, -- 8-digit custom code
  user_id UUID REFERENCES auth.users(id), 
  name TEXT,
  gender TEXT,
  email TEXT UNIQUE,
  avatar_url TEXT, -- NOUVEAU : Photo de profil
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CLOTHES TABLE
CREATE TABLE IF NOT EXISTS clothes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
  type TEXT,
  color TEXT,
  season TEXT,
  activity TEXT DEFAULT 'Quotidien',
  icon TEXT,
  image_url TEXT,
  last_worn_date TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. SECURITY (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clothes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can only access their own profile" ON profiles;
CREATE POLICY "Users can only access their own profile" 
ON profiles FOR ALL 
USING (auth.uid() = user_id OR (user_id IS NULL AND id IS NOT NULL)); -- Autorise l'accès temporaire via code

DROP POLICY IF EXISTS "Users can only access their own clothes" ON clothes;
CREATE POLICY "Users can only access their own clothes" 
ON clothes FOR ALL 
USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = clothes.profile_id 
    AND (profiles.user_id = auth.uid() OR profiles.user_id IS NULL)
  )
);

-- 4. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_clothes_profile ON clothes(profile_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_email_unique ON profiles(email) WHERE email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON profiles(user_id);

-- 5. STORAGE BUCKETS (Note: Manual creation in dashboard recommended)
-- clothes-images: Public=true
-- avatars: Public=true

-- 6. TRIGGER UPDATED_AT
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_profiles_modtime ON profiles;
CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

DROP TRIGGER IF EXISTS update_clothes_modtime ON clothes;
CREATE TRIGGER update_clothes_modtime BEFORE UPDATE ON clothes FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
