-- ########################################################
-- # MASTER SCHEMA FOR DRESSFLOW - SUPABASE
-- ########################################################

-- 1. PROFILES TABLE
CREATE TABLE IF NOT EXISTS profiles (
  id TEXT PRIMARY KEY, -- 8-digit custom code
  name TEXT,
  gender TEXT,
  email TEXT UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. CLOTHES TABLE
CREATE TABLE IF NOT EXISTS clothes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id TEXT REFERENCES profiles(id) ON DELETE CASCADE,
  type TEXT,
  color TEXT,
  season TEXT,
  activity TEXT DEFAULT 'Quotidien',
  icon TEXT,
  image_url TEXT,
  last_worn_date TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. STORAGE SETUP
-- Assure-toi de créer manuellement le bucket 'clothes-images' s'il n'existe pas
-- INSERT INTO storage.buckets (id, name, public) VALUES ('clothes-images', 'clothes-images', true) ON CONFLICT (id) DO NOTHING;

-- 4. SECURITY (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clothes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Profiles Access" ON profiles;
CREATE POLICY "Public Profiles Access" ON profiles FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Public Clothes Access" ON clothes;
CREATE POLICY "Public Clothes Access" ON clothes FOR ALL USING (true) WITH CHECK (true);

-- 5. PERFORMANCE INDEXES
CREATE INDEX IF NOT EXISTS idx_clothes_profile ON clothes(profile_id);
CREATE INDEX IF NOT EXISTS idx_clothes_type ON clothes(type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_profiles_email_unique ON profiles(email) WHERE email IS NOT NULL;

-- 6. AUTOMATIC UPDATED_AT TRIGGER
CREATE OR REPLACE FUNCTION update_modified_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_profiles_modtime ON profiles;
CREATE TRIGGER update_profiles_modtime BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE PROCEDURE update_modified_column();

DROP TRIGGER IF EXISTS update_clothes_modtime ON clothes;
CREATE TRIGGER update_clothes_modtime BEFORE UPDATE ON clothes FOR EACH ROW EXECUTE PROCEDURE update_modified_column();
